<img src="../Images/PixelPC.gif" />

# Home Learning Tasks
#### 🌸Session 5: NumPy | Tuesday, 08/02/2022

_________________________________________________________________________________________________________________

### Lesson Contents

- What is NumPy?
- Using the NumPy Library
- Lists v Arrays
- Slicing Arrays

_________________________________________________________________________________________________________________________

<img src="../Images/NumPy_logo_small.png" />

"NumPy is a library for the Python programming language, adding support for large, multi-dimensional arrays and matrices, along with a large collection of high-level mathematical functions to operate on these arrays."

##### ***1.Create a 1D array of numbers from 0 to 9***

In [2]:
import numpy as np

In [33]:
list = np.array([0,1,2,3,4,5,6,7,8,9])
print(list)

[0 1 2 3 4 5 6 7 8 9]


In [34]:
list = np.arange(10)
print(list)

[0 1 2 3 4 5 6 7 8 9]


##### ***2.Create a 3×3 NumPy array of all Boolean value Trues***

In [35]:
array1s = np.ones(9).reshape(3,3)
print(array1s)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [36]:
arraybool = np.zeros([3,3], dtype=bool)
print(arraybool)

[[False False False]
 [False False False]
 [False False False]]


In [37]:
arraybool = np.ones([3,3], dtype=bool)
print(arraybool)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


##### ***3.Extract all odd numbers from array of 1-10***

In [38]:
list = np.array([1,2,3,4,5,6,7,8,9,10])
print("Even number(s):", list[1::2])

Even number(s): [ 2  4  6  8 10]


In [39]:
arrayList = np.array([1,2,3,4,5,6,7,8,9,10])
print("Odd number(s):", list[arrayList % 2 != 0])

Odd number(s): [1 3 5 7 9]


##### ***4.Replace all odd numbers in an array of 1-10 with the value -1***

In [43]:
arrayxList = np.array([1,2,3,4,5,6,7,8,9,10])
for i in range(len(arrayxList)):                              #len = length
    if arrayxList[i] % 2 != 0:
        arrayxList[i] = -1

print(arrayxList)

[-1  2 -1  4 -1  6 -1  8 -1 10]


##### ***5.Convert a 1D array to a 2D array with 2 rows***

In [41]:
array1D = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

array2D = array1D.reshape(2, 5) 

print(array2D)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


##### ***6.Create two arrays a and b, stack these two arrays vertically. Use the  np.dot and np.sum to calculatetotals*** 🚩

In [6]:
a = np.arange(1,10).reshape(3,3)
b = np.arange(10,19).reshape(3,3)
c = np.dot(a,b)
print(c)
d = np.sum(c,axis = 1)
print(d)



[[ 84  90  96]
 [201 216 231]
 [318 342 366]]
[ 270  648 1026]


##### ***Extension:***  🚩

1.Create the following pattern without hardcoding. Use only NumPy  functions. #array([1,1,1,2,2,2,3,3,3,1,2,3,1,2,3,1,2,3])

2.In two arrays a ( 1,2,3,4,5) and b ( 4,5,6,7,8,9) –remove allrepeating  items present in arrayb

3.Get all items between 3 and 7 from a and b and sum themtogether

In [4]:
# Don't hard code basically means, you should rely on your code, your logic, your program, and you should not write things out by hand or do computation in your head.

one = np.ones(3)
two = one + one
three = one * 3

repeat = np.arange(1,4)
print(repeat)
tile = np.tile(repeat, 3)
print(tile)
final = np.concatenate((one, two, three, tile))
print(final)

[1 2 3]
[1 2 3 1 2 3 1 2 3]
[1. 1. 1. 2. 2. 2. 3. 3. 3. 1. 2. 3. 1. 2. 3. 1. 2. 3.]
